package com.rus_cns_mon.pub_rus_cns_all_data_rule_editing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pub_cns_combined_flattened implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public pub_cns_combined_flattened() {
    }




}